name: Run Locust Tests on Commit
on:
  push:
    branches:
      - main

jobs:
  locust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt #Rajout des requirements pour run les scripts

      - name: Start Flask server
        run: |
          # Command to start your Flask server
          python server.py &
          echo "Waiting for Flask server to start"
          sleep 30

      - name: Running locust tests
        run: |
          # Command to start your Flask server
          locust -f your_locust_file.py --host=http://127.0.0.1:5000 --users 10000 --spawn-rate 100 --headless --run-time 2m &
          echo "Waiting for locust to run"
          sleep 120

      - name: Clean up the processes
        run: |
          pkill -f locust &
          pkill -f server.py